<nav class="navbar navbar-fixed-top navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main_menu">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/dataextract/App">
                DataExtract
            </a>
        </div>
        <div class="collapse navbar-collapse" id="main_menu">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Seções</a></li>
            </ul>
        </div>
    </div>
</nav>
